name: equipo_naranja_reto6
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn=1.3.2
  - imbalanced-learn
  - requests
  - beautifulsoup4
  - wordcloud
  - chardet
  - joblib
  - missingno
  - holidays
  - umap-learn
  - yellowbrick
  - hdbscan
